//------Generated by the Framework and can be changed-----//
//------Collect Sensor Data from Smartphone Accelerometer Sensor-----//

package br.ufc.realer_2.model.mapek.monitoring

import android.hardware.SensorEvent
import br.ufc.realer_2.model.entities.sensors.ValuesACC

class CollectAcc:ICollectorData {
    private var myData:String = ""
     override fun collectData(event: SensorEvent ?):Any {
         myData = event!!.values[0].toString()+","+event!!.values[1].toString() +","+event!!.values[2].toString()
         return FormatData(myData)
     }

    override fun FormatData(myData:String):Any{
        val novosValoresACC:Any = ValuesACC((myData.split(",")[0].toDouble()),
            myData.split(",")[1].toDouble(),
            myData.split(",")[2].toDouble());
        return novosValoresACC
    }

    override fun getValueData():String {
        return myData
    }


}