//------Generated by the Framework and must not be changed-----//
//------Collect Sensor Data from Smartphone Classes Interface-----//

package br.ufc.realer_2.model.mapek.monitoring

import android.hardware.SensorEvent

interface ICollectorData {
        fun collectData(event: SensorEvent?):Any
        fun FormatData(value:String):Any
        fun getValueData(): String
}