//------Generated by the Framework and can be changed-----//
//------Sample get user profile from Google API----//

package br.ufc.realer_2.controllers

import android.content.Intent
import android.widget.TextView
import br.ufc.realer_2.model.utils.GoogleApiUtil
import br.ufc.realer_2.ui.CommonActivities.BaseActivity
import br.ufc.realer_2.ui.CommonActivities.LoginActivity
import java.lang.RuntimeException

class ProfileController(private val activity: BaseActivity) {
    private var googleApiClient: GoogleApiUtil = GoogleApiUtil(activity)

  /*  fun logOut() {
        googleApiClient.logOut(this)
    }
*/
    fun start() {
        googleApiClient.signIn()
    }

    fun callLogin() {
        activity.startActivity(Intent(activity.baseContext, LoginActivity::class.java))
        activity.finish()
    }

    fun setName(textView: TextView) {
        try {
            if (googleApiClient.isLogged()) {
                textView.text = googleApiClient.getName()
            }
        }catch (e: RuntimeException){
            callLogin()
        }
    }

    fun getName():String{
        try {
            if (googleApiClient.isLogged()) {
                return googleApiClient.getName()
            }
        }catch (e: RuntimeException){
            callLogin()
        }

        return ""
    }

    fun getEmail():String{
        try {
            if (googleApiClient.isLogged()) {
                return googleApiClient.getEmail()
            }
        }catch (e: RuntimeException){
            callLogin()
        }

        return ""
    }

    fun setEmail(textView: TextView) {
        try {
            if (googleApiClient.isLogged()) {
                textView.text = googleApiClient.getEmail()
            }
        }catch (e: RuntimeException){
            callLogin()
        }
    }

    fun isLogged(): Boolean{
        if(googleApiClient != null){
            return googleApiClient.isLogged()
        }
        return false
    }
}