//------Generated by the Framework and can be changed-----//
//------Unity of Work Pattern Interface-----//

package br.ufc.realer_2.model.dao.interfaces

interface IUnityofWork {
    fun transaction()
    fun commit()
    fun rollback()
}