//------Generated by the Framework and can be changed-----//
//------Base Activity for Main Activity and Model Functions-----//
package br.ufc.realer_2.ui.CommonActivities

import android.content.res.AssetManager
import android.os.Bundle
import android.os.PersistableBundle
import android.view.Gravity
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import br.ufc.realer_2.model.mapek.monitoring.GoogleFit.GoogleFitAPI
import br.ufc.realer_2.model.entities.KnowledgeRepresentation
import br.ufc.realer_2.model.entities.sensors.ValuesSensor
import br.ufc.realer_2.model.entities.sensors.typeSensor
import br.ufc.realer_2.model.mapek.knowledge.KnowledgeManagement
import br.ufc.realer_2.model.mapek.monitoring.CollectAcc
import br.ufc.realer_2.model.mapek.monitoring.CollectGyr
import br.ufc.realer_2.controllers.DataController

abstract class BaseActivity : AppCompatActivity() {

    private lateinit var toast: Toast

    lateinit var dataController: DataController
    lateinit var baseDirectory:String
    lateinit var assetManager: AssetManager
    var knowledgeRepresentation: KnowledgeRepresentation? = null
    var energy: Double? = null
    var actions: MutableList<String> = mutableListOf<String>()
    var sensors = mutableListOf<typeSensor>()
    var datas = mutableListOf<ValuesSensor>()

    val googleFitAPI = GoogleFitAPI(this)
    val knowledgeManagement = KnowledgeManagement(this)

    //Sensor Collect Data Class (has needed declare all sensors that collect data from cellphone)
    //Similar ao CAC do LOCCAm
    var collectAcc = CollectAcc()
    var collectGyr = CollectGyr()

    companion object{lateinit var finalStatus: String}



    override fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?) {
        super.onCreate(savedInstanceState, persistentState)
    }

    fun showLongToast(text: String, isCenter: Boolean) {
        showToast(text, Toast.LENGTH_LONG, isCenter)
    }

    fun showShortToast(text: String, isCenter: Boolean) {
        showToast(text, Toast.LENGTH_SHORT, isCenter)
    }

    private fun showToast(text: String, mode: Int, isCenter: Boolean){
        toast = Toast.makeText(applicationContext, text, mode)
        if(isCenter){
            toast.setGravity(Gravity.CENTER, 0, 0)
        }
        toast.show()
    }


}