//------Generated by the Framework and can be changed-----//
package br.ufc.realer_2.model.entities.sensors

//------Type Sensor Enum
//------Is needed Use the Same Identifier of the Classification Graph if you can use the Graph Artifact
enum class typeSensor {
    //podem adicionar mais tipos de sensores
    ACC, GYR, GPS, WIFI, MIC
}