//------Generated by the Framework and can be changed-----//
package br.ufc.realer_2.model.entities.sensors

//------Sample of ACC Tri-Axial Values-----//
class ValuesACC(val eixoX:Double, val eixoY:Double, val eixoZ:Double) {
}