//------Generated by the Framework and must not be changed-----/
//------From Observer Pattern Interface-----//

package br.ufc.realer_2.model.mapek.observer

interface IExecutionObserver {
        fun update()
}