//------Generated by the Framework and must not be changed-----/
//------From Observer Pattern Interface-----//

package br.ufc.realer_2.model.mapek.observer

interface IPlanningObservable {
    val observers: MutableList<IPlanningObserver>

    fun add(observer: IPlanningObserver){
        observers.add(observer)
    }

    fun sendUpdateEvent(){
        observers.forEach{ it.update() }
    }
}