//------Generated by the Framework and can be changed-----//
//------Action Sample Class-----//

package br.ufc.realer_2.model.mapek.execution

import android.util.Log
import br.ufc.realer_2.ui.AlertActivity
import br.ufc.realer_2.ui.CommonActivities.BaseActivity
import task.Task2

class LightAction:Task2() {

    lateinit var context:BaseActivity

    override fun recebeToken(o: Any?) {}

    override fun retornaToken(): Any? {
        return null
    }

    override fun executar() {
        //MainActivity.flagMonitoring = true
        //MainActivity.texto = "Danger"
        Log.i("Light status",BaseActivity.finalStatus !! )

        AlertActivity.actions.add("luz")
    }

    override fun retorno(): Any? {
        return null
    }

    override fun evaluate(o: Any) {
        val result = o as Pair<String,BaseActivity>
        BaseActivity.finalStatus  = o.first

        ///Begin verification of special Status
        if (BaseActivity.finalStatus !!.contains("Clapping Standing") || BaseActivity.finalStatus !!.contains("Fall") ||
        BaseActivity.finalStatus !!.contains("Hitting a wall"))
            executar()
        ///End verification of special Status

    }

    override fun run() {
        executar()
    }
}