//------Generated by the Framework and can be changed-----//
//------Action Sample Class-----//

package br.ufc.realer_2.model.mapek.execution

import android.util.Log
import br.ufc.realer_2.ui.AlertActivity
import br.ufc.realer_2.ui.MainActivity
import br.ufc.realer_2.ui.CommonActivities.BaseActivity
import task.Task2

class TextAction: Task2() {

    lateinit var context:BaseActivity

    override fun recebeToken(o: Any?) {}

    override fun retornaToken(): Any? {
        return null
    }

    override fun executar() {
        //MainActivity.texto = "Danger"
        Log.i("Text status",BaseActivity.finalStatus !! )
        AlertActivity.actions.add("texto")
        //set alert information to call AlertActivity
        MainActivity.alarm = true
    }

    override fun retorno(): Any? {
        return null
    }

    override fun evaluate(o: Any) {
        val result = o as Pair<String,BaseActivity>
        BaseActivity.finalStatus  = o.first

        //if need to use context data
        context = o.second

        ///Inicio verificação de Status especiais
        if (BaseActivity.finalStatus !!.contains("Clapping Standing") || BaseActivity.finalStatus !!.contains("Fall") ||
            BaseActivity.finalStatus !!.contains("Hitting a wall"))
            executar()
        ///Fim de verificação de Status especiais
    }

    override fun run() {
        executar()
    }
}