//------Generated by the Framework and must not be changed-----//
//------Google API Util Functions-----//
package br.ufc.realer_2.model.utils

import android.annotation.SuppressLint
import android.content.Intent
import android.net.Uri
import br.ufc.realer_2.ui.CommonActivities.BaseActivity
import com.google.android.libraries.identity.googleid.GetGoogleIdOption


@SuppressLint("CheckResult")
class GoogleApiUtil (private val activity: BaseActivity) {
    var account: GoogleSignInAccount? = null
    private var client: GoogleSignInClient

    private var id = "152860001735-8ohoj0n2ictmcmit69pl2aauspdd2g2d.apps.googleusercontent.com"

    init {

        val googleIdOption: GetGoogleIdOption = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(true)
            .setServerClientId(id)
            .setAutoSelectEnabled(true)
            // nonce string to use when generating a Google ID token
            .setNonce(nonce)
            .build()

        client = GetCredentialRequest = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        )
    }

    fun signIn() {
        activity.startActivityForResult(client.signInIntent, Constants.SIGN_IN)
        val task: Task<GoogleSignInAccount> = client.silentSignIn()

        if (task.isSuccessful) {
            account = task.result
        }
    }

    fun googleResult(data: Intent?): Boolean? {
        if(data != null){
            return Auth.GoogleSignInApi.getSignInResultFromIntent(data)?.isSuccess
        }
        return false
    }

    fun isLogged():Boolean{
        val lastSignedInAccount = GoogleSignIn.getLastSignedInAccount(activity.applicationContext)
        if(lastSignedInAccount != null){
            account = lastSignedInAccount
            return true
        }
        return false
    }

    fun getName(): String {
        return account?.displayName!!
    }

    fun getEmail(): String {
        return account?.email!!
    }

    fun getImage(): Uri? {
        return account?.photoUrl
    }

}