//------Generated by the Framework and must not be changed-----//
//------Device Permission Util Functions-----//
package br.ufc.realer_2.model.utils

import android.Manifest
import android.content.pm.PackageManager
import android.util.Log
import android.widget.Toast
import androidx.core.app.ActivityCompat
import br.ufc.realer_2.ui.CommonActivities.BaseActivity

class PermissionsUtil {
    fun checkDevicePermission(context: BaseActivity) : Boolean {
        if (ActivityCompat.checkSelfPermission(
                context,
                Manifest.permission.ACTIVITY_RECOGNITION
            ) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(
                context,
                Manifest.permission.ACTIVITY_RECOGNITION
            ) != PackageManager.PERMISSION_GRANTED
        ) {
            Toast.makeText(context, "No Permissions", Toast.LENGTH_LONG).show()
            Log.i("Permissions", "Permissions Granted")
            return false
        } else {
            Log.i("Permissions", "Has permissions")
            //Toast.makeText(this, "Has Permissions", Toast.LENGTH_LONG).show()
            return true
        }

    }

    //Request Device Permissions
    //ADD Here the permissios needed for your app
    fun requetPermission(context: BaseActivity){
        ActivityCompat.requestPermissions(
            context,
            arrayOf(
                Manifest.permission.WRITE_EXTERNAL_STORAGE,
                Manifest.permission.READ_EXTERNAL_STORAGE,
                Manifest.permission.ACCESS_COARSE_LOCATION,
                Manifest.permission.ACCESS_FINE_LOCATION,
                Manifest.permission.BODY_SENSORS,
                Manifest.permission.ACTIVITY_RECOGNITION,
                Manifest.permission.CAMERA
            ),
            0
        )
        Log.i("Permissions", "Permissions Granted")
    }
}