//------Generated by the Framework and must not be changed-----//
package br.ufc.realer_2.model.entities

//------Entity representing a simple context information used for Adaptation Planning and Analysis-----//
class Context (val name:String, var value:Any) {
}