//------Generated by the Framework and must not be changed-----//
//------Entity representing an Edge ModelsFinalStatus for Knowledge Representation based on Classification Graph Template-----//
package br.ufc.realer_2.model.entities

class EdgeModelsFinalStatus(val vModel: VerticeModel, val vFinalStatus: VerticeFinalStatus, var probability:Double?=null) {
}