//------Generated by the Framework and must not be changed-----//
//------Entity representing an Edge FeatureModel for Knowledge Representation based on Classification Graph Template-----//
package br.ufc.realer_2.model.entities

class EdgeFeatureModel(val vFeature:VerticeFeature, val vModel: VerticeModel, val contexts: MutableList<Context>?=null) {
}