//------Generated by the Framework and must not be changed-----//
//------Entity representing an Edge SensorFeature for Knowledge Representation based on Classification Graph Template-----//

package br.ufc.realer_2.model.entities

class EdgeSensorFeature (val vSensor: VerticeSensor, val vFeature: VerticeFeature, val contexts: MutableList<Context>?=null) {
}