//------Generated by the Framework and must not be changed-----//
//------Entity representing a Knowledge Representation based on Classification Graph Template-----//
package br.ufc.realer_2.model.entities

class KnowledgeRepresentation (var edgeSensorFeature: MutableList<EdgeSensorFeature>,
                               var edgeFeaturesModel: MutableList<EdgeFeatureModel>,
                               var edgeModelsFinalStatus: MutableList<EdgeModelsFinalStatus>){

}