//------Generated by the Framework and must not be changed-----//
//------Entity representing a Vertice Values Feature for Knowledge Representation based on Classification Graph Template-----//
package br.ufc.realer_2.model.entities

class ValuesFeatures (val idSensor:String, val name:String) {}