//------Generated by the Framework and must not be changed-----//
//------Entity representing a Vertice Model for Knowledge Representation based on Classification Graph Template-----//
package br.ufc.realer_2.model.entities

import org.tensorflow.lite.Interpreter;

class VerticeModel(val modelName: String, val inFeature:Int, val outFeature: Int, var model:Interpreter?=null) {
    fun setSmartModel(newmodel: Interpreter?){
        model = newmodel
    }
}