//------Generated by the Framework and must not be changed-----//
//------Entity representing a Vertice Feature for Knowledge Representation based on Classification Graph Template-----//
package br.ufc.realer_2.model.entities

class VerticeFeature(val feature: Double, val featureName:ValuesFeatures) {
}